services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: arch_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: arch_web
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: arch_db
    environment:
      MYSQL_DATABASE: arch_planner
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
